metaframe/__init__.py
metaframe/loader/metaframe_loader.py
setup.py
tests/unit/extractor/test_presto_loop_extractor.py

Just a simple refactor of the PrestoLoopExtractor test.

chore: refactor presto loop test, and fix version in setup.py.

---

.github/workflows/tests.yml
Makefile

https://github.com/rsyi/metaframe/issues/8

feat: add codecov to actions.

---

shell/mf

https://github.com/rsyi/metaframe/issues/19

fix: broken sed statement.

---

.github/workflows/tests.yml
metaframe/__init__.py
metaframe/extractor/base_bigquery_extractor.py
metaframe/extractor/bigquery_metadata_extractor.py
metaframe/models/connection_config.py
metaframe/utils/extractor_wrappers.py
requirements.txt
tests/unit/extractor/test_bigquery_metadata_extractor.py

Modify and merge in the amundsen bigquery extractor and add all relevant pathways so configuration can be passed in through the `connections.yaml` file.

Add bigquery extraction pathway

---

hooks/hook-metaframe.extractor.snowflake_metadata_extractor.py
metaframe/extractor/snowflake_metadata_extractor.py
metaframe/utils/extractor_wrappers.py
metaframe/utils/task_wrappers.py

Copied and modified (for consistency in database/catalog relationships and naming conventions) the snowflake extractor from amundsen's databuilder, and added support by default to the library. We should consider requiring installation with explicit flags for certain drivers in the future, so we all users don't have to download all drivers... 
Addresses:
https://github.com/rsyi/metaframe/issues/4

feat: add snowflake connector.

---

cli/src/main.rs
databuilder/whalebuilder/loader/whale_loader.py
databuilder/whalebuilder/transformer/markdown_transformer.py
databuilder/whalebuilder/utils/extractor_wrappers.py

* Adds logic to `WhaleLoader` to display partition information.
* Minor chore: consolidate a bunch of `if let`s into a match.

Add partition logic

---

databuilder/build_script.py
databuilder/requirements.txt
databuilder/tests/unit/extractor/test_presto_loop_extractor.py
databuilder/whalebuilder/extractor/bigquery_watermark_extractor.py
databuilder/whalebuilder/extractor/presto_loop_extractor.py
databuilder/whalebuilder/extractor/presto_table_metadata_extractor.py
databuilder/whalebuilder/loader/whale_loader.py
databuilder/whalebuilder/task/__init__.py
databuilder/whalebuilder/transformer/markdown_transformer.py
databuilder/whalebuilder/utils/__init__.py
databuilder/whalebuilder/utils/extractor_wrappers.py
databuilder/whalebuilder/utils/task_wrappers.py

Change manifest interactions.
Fix a bugs where having multiple warehouses would cause overwriting.

Change manifest interactions, supporting where clause for presto; fix multiple warehouse bugs

---

cli/src/warehouse.rs
databuilder/whalebuilder/loader/whale_loader.py
databuilder/whalebuilder/models/connection_config.py
databuilder/whalebuilder/transformer/markdown_transformer.py
databuilder/whalebuilder/utils/extractor_wrappers.py
databuilder/whalebuilder/utils/task_wrappers.py

Adds support for
* Hive metastore
* Postgres
* Redshift
(using Amundsen's connectors!)

Set up connectors

---

cli/src/filesystem.rs
cli/src/lib.rs
cli/src/main.rs
cli/src/serialization.rs
cli/src/skimmer.rs
cli/src/utils.rs
cli/src/warehouse.rs

ran `cargo fmt` against cli code. Can follow up with a PR for a cargo/rust workflow if that's welcome.

chore: run cargo format

---

.github/workflows/cargo-ci.yml
cli/src/lib.rs
cli/src/main.rs
cli/src/skimmer.rs
cli/src/warehouse.rs

* rerun cargo fmt to fix issues introduced in
https://github.com/biomunky/whale/commit/7cc42add0859459139fd3301204746ce89a739cd,
required to make workflow pass
* add workflow that runs fmt, clippy, check and tests

chore: Add Cargo Github Workflow

---

pipelines/setup.py
pipelines/whale/transformer/markdown_transformer.py

Addresses this: https://github.com/dataframehq/whale/issues/54

fix: broken glue extractor when there is a description

---

.github/workflows/python-ci.yml
pipelines/tests/unit/extractor/test_bigquery_metadata_extractor.py
pipelines/tests/unit/utils/test_task_wrappers.py

Closes https://github.com/dataframehq/whale/issues/74

fix: mock google.auth.default to prevent Google API calls in tests

---

Makefile
pipelines/whale/utils/__init__.py
pipelines/whale/utils/paths.py

Closes https://github.com/dataframehq/whale/issues/52

chore: improved file paths and manifest copy function

---

pipelines/setup.py
pipelines/whale/extractor/metric_runner.py
pipelines/whale/loader/whale_loader.py
pipelines/whale/utils/parsers.py

Closes https://github.com/dataframehq/whale/issues/83 and https://github.com/dataframehq/whale/issues/81.

Enable continuation when metric is not well-defined; fix incorrect formatting with multiple metrics

---

pipelines/setup.py
pipelines/tests/unit/extractor/test_glue_extractor.py
pipelines/whale/extractor/glue_extractor.py
pipelines/whale/models/connection_config.py
pipelines/whale/transformer/markdown_transformer.py
pipelines/whale/utils/__init__.py
pipelines/whale/utils/extractor_wrappers.py

Closes https://github.com/dataframehq/whale/issues/90.

fix: by default do not parse location

---

pipelines/setup.py

Exclude tests/ from whale-pipelines wheel

---

.github/workflows/cd.yml
pipelines/setup.py

Addresses https://github.com/dataframehq/whale/issues/97.
Also, advance the version.

fix: build setup.py within the pipelines directory

---

docs/features/metrics.md

In order to finish https://github.com/dataframehq/whale/issues/80 we should follow up [this implementation PR](https://github.com/dataframehq/whale/pull/101) with documentation. This PR adds the corresponding documentation.
- Let me know if the wording makes sense
- I added a few comments to the code on my motivation for the code changes

Add documentation on Slack alerts

---

pipelines/whale/extractor/postgres_metadata_extractor.py

In this PR:
- SQL changes for postgres extractor to pull an `is_view` flag
- Modifications to Postgres Extractor to pull `is_view` flag into TableMetadata model

Add support for Postgres table views

---

Makefile
pipelines/requirements.txt

@rsyi fixed the debian installation error. `grpcio` needed a bump in the `requirements.txt`

fix: broken debian installation (#116)

---

cli/src/lib.rs
pipelines/setup.py

Closes https://github.com/dataframehq/whale/issues/118.

fix: source -> .

---

.gitignore

Taken from here: https://github.com/github/gitignore/blob/master/Python.gitignore

Ignore virtual environment in gitignore

---

pipelines/build_script.py
pipelines/setup.py

Closes https://github.com/dataframehq/whale/issues/134.

hotfix: broken etl reference

---

pipelines/tests/unit/extractor/test_postgres_metadata_extractor.py
pipelines/tests/unit/extractor/test_splice_machine_metadata_extractor.py
pipelines/tests/unit/test_init.py
pipelines/whale/extractor/postgres_metadata_extractor.py
pipelines/whale/extractor/splice_machine_metadata_extractor.py
services/slack_access_token.py
services/tests/test_slack_access_token.py

Ran `black .` once to re-format all files

Running black formatter

---

pipelines/setup.py
pipelines/whale/models/connection_config.py

Closes https://github.com/dataframehq/whale/issues/154.

feat: add in ability to specify role.

---

cli/Cargo.toml
pipelines/setup.py
pipelines/whale/extractor/base_postgres_metadata_extractor.py
pipelines/whale/extractor/redshift_metadata_extractor.py
pipelines/whale/utils/extractor_wrappers.py

Addresses #164 by hard forking the redshift extractor and pulling it into whale.

Fix redshift

---

pipelines/tests/unit/loader/test_whale_loader.py
pipelines/tests/unit/models/test_index_metadata.py
pipelines/tests/unit/models/test_table_metadata.py
pipelines/tests/unit/utils/test_extractor_wrappers.py
pipelines/whale/models/column_metadata.py
pipelines/whale/models/table_column_stats.py
pipelines/whale/utils/__init__.py

chore: format

---

cli/Cargo.toml
pipelines/setup.py
pipelines/whale/__init__.py
pipelines/whale/utils/parsers.py

Also addresses https://github.com/dataframehq/whale/issues/148 :)

hotfix: execution in named cells was breaking

---

pipelines/requirements.txt
pipelines/whale/engine/sql_alchemy_engine.py
pipelines/whale/extractor/presto_table_metadata_extractor.py
pipelines/whale/models/connection_config.py
pipelines/whale/utils/extractor_wrappers.py

connect_args which is vital incase of https connection for presto/trino could be define like this in ~/.whale/config/connections.yaml
```
connect_args: {'protocol':'https'}
```

add support connect_args for presto/trino connector

---

pipelines/whale/extractor/hive_table_metadata_extractor.py
pipelines/whale/utils/extractor_wrappers.py

Resolving https://github.com/hyperqueryhq/whale/issues/196 by cooking hivemetastore to adapt with whale's extractor interfaces

Fix syncing hive metastore not compatible
