.gitignore
hooks/hook-metaframe.extractor.amundsen_neo4j_metadata_extractor.py
hooks/hook-metaframe.extractor.presto_loop_extractor.py
metaframe/loader/metaframe_loader.py
tests/unit/loader/test_metaframe_loader.py
tests/unit/transformer/test_markdown_transformer.py

Addresses the following issues:
https://github.com/rsyi/metaframe/issues/8
https://github.com/rsyi/metaframe/issues/9
https://github.com/rsyi/metaframe/issues/10

chore: modify and add test for metaframe loader; add inits for codecov.

---

.gitignore
metaframe/engine/mixins/presto_commands_mixin.py
metaframe/engine/presto_engine.py
metaframe/example/sample_build_script.py
metaframe/extractor/amundsen_neo4j_metadata_extractor.py
metaframe/extractor/bigquery_metadata_extractor.py
metaframe/extractor/presto_loop_extractor.py
metaframe/extractor/snowflake_metadata_extractor.py
metaframe/loader/metaframe_loader.py
metaframe/models/connection_config.py
metaframe/models/presto_watermark.py
metaframe/models/table_metadata.py
metaframe/transformer/markdown_transformer.py
metaframe/utils/__init__.py
metaframe/utils/extractor_wrappers.py
setup.py
tests/unit/engine/test_presto_engine.py
tests/unit/extractor/test_presto_loop_extractor.py
tests/unit/extractor/test_snowflake_metadata_extractor.py
tests/unit/loader/test_metaframe_loader.py
tests/unit/transformer/test_markdown_transformer.py

* Refactor all instances of `cluster` to `catalog`, since this appears to be the appropriate term for presto, snowflake, and `information_schema` entries. **This represents a substantial change in the connections.yaml syntax -- moving forward, `catalog` needs to be specified where `cluster` was previously specified.**
* Add snowflake tests.

chore: refactor catalog and add snowflake tests

---

databuilder/build_script.py
databuilder/tests/unit/utils/test_extractor_wrappers.py
databuilder/whalebuilder/task/__init__.py
databuilder/whalebuilder/utils/task_wrappers.py

* Sometimes watermark/usage/etc. extractors can fail because of insufficient permissions (e.g. see the current state of the [whale bigquery demo](https://github.com/dataframehq/whale-bigquery-public-data/actions)). Wrapped all non-metadata extraction tasks in a `try/except` to allow all remaining clean-up work to pass through.
* Improve logging: in the current state of the app, we were (a) not surfacing module-level logs to stdout or cron.log and (b) had no expiration for these logs. This PR modifies the build_script.py file so both of these issues are fixed. For (b), I've used a `RotatingFileHandler`, so the last 5 backups are saved up to ~50 mb each. This is probably overkill, but best to have a safeguard in place.
* Add a missing postgres/redshift test.

Enable try/except; improve logging

---

cli/src/warehouse.rs
pipelines/requirements.txt
pipelines/tests/unit/utils/test_extractor_wrappers.py
pipelines/tests/unit/utils/test_task_wrappers.py
pipelines/whale/utils/extractor_wrappers.py
pipelines/whale/utils/task_wrappers.py

Addresses this: https://github.com/dataframehq/whale/issues/46
* Uses the amundsendatabuilder `GlueExtractor` to scrape directly from aws glue using the boto3 API. Creates a dedicated wrapper that handles this.
* Adds boto3 as a default requirement.
* Adds a test for the new configurer.

feat: add glue support.

---

.github/workflows/cargo-ci.yml
.github/workflows/tests.yml

Could be more selective about branch names 🤷.
Quickly tested in my fork and it does what I expect however I'm not too familiar with workflows.

 chore: cargo-ci should only run when cli/ is modified #58 

---

cli/src/filesystem.rs

Covers #59 and minor changes
* Update `No such file or directory` panics to resource names.
Current panics state that resources can't be read/written but do not
include information about which resource is being accessed. This change
uses `.unwrap_or_else()` to panic with an explicitly named resource
* many of the get_* functions were using let bindings, these have been
removed in favor of a direct return
* moved the longer functions above the collection of shorter get_* functions.

chore: Panic with named resources & small tidy-up

---

cli/src/lib.rs
cli/src/utils.rs

Covers https://github.com/dataframehq/whale/issues/63
Looks like fgrep is deprecated (1,2) so I've replaced it with 'just' grep.
grep -E is then used like `grep -E \"wh|whale pull` to match wh or whale
followed by pull.
I've tested this on a mac and an Ubuntu container with echo-ed text and the whale generated crontab entry.
sidenote: think it's probably worth creating an issue to increase the rust test coverage.
1. https://unix.stackexchange.com/questions/383448/why-is-direct-invocation-as-either-egrep-or-fgrep-deprecated
2. https://linuxhandbook.com/grep-egrep-fgrep/

fix: crontab failed to register

---

.editorconfig
CONTRIBUTING.md
README.md

Targets https://github.com/dataframehq/whale/issues/72
[Editorconfig](https://editorconfig.org/) is a tool designed to help
maintain coding standards for multiple developers working on the same
project with different editors. I've added a simple config file in this PR 
and applied the rules to the CONTRIBUTING.md and README.md, note
removal of trailing whitespace.
Perhaps we should document a setup process for contributing? Which
tools folks will have to install and how, part of this should include the above,
although some editors ship with support (VSCode does not)

chore: Add editorconfig

---

pipelines/setup.py
pipelines/tests/unit/extractor/test_glue_extractor.py
pipelines/whale/extractor/glue_extractor.py
pipelines/whale/loader/whale_loader.py
pipelines/whale/utils/extractor_wrappers.py

Closes https://github.com/dataframehq/whale/issues/86.
With this:
* Glue table names are parsed more effectively (rather than `schema_table` or `catalog_schema_table`, we write `catalog.schema.table` by parsing the provided glue name and returning the properly-formatted payload).
* Use the database/instance name as a separate directory, by using the formatting "connection_name/database/catalog.schema.table". If `name` isn't given in the connections.yaml file, you'll instead get: "database/catalog.schema.table". If exclusively using Glue, this reduces the complexity of the file structure nicely.
I don't believe anyone other than @rubenssoto is using this extractor (at the moment), but if you are, **please open an issue and I'd be happy to provide a migration script!** Breaking semantic …

feat: better parsing of glue tables; enable directory file structure

---

pipelines/requirements.txt
pipelines/tests/unit/extractor/test_bigquery_metadata_extractor.py
pipelines/whale/extractor/base_bigquery_extractor.py
pipelines/whale/extractor/bigquery_metadata_extractor.py
pipelines/whale/models/table_metadata.py
pipelines/whale/utils/__init__.py

- Using `datacatalog_v1` Python client to fetch tags for a given BQ table
- Added the tags data to `TableMetadata` and `ColumnMetadata`  where appropriate
- Also added labels to `TableMetadata`

feat: added labels and tags fetching for BigQuery

---

docs/features/metrics.md
pipelines/tests/unit/extractor/test_glue_extractor.py
pipelines/tests/unit/extractor/test_metric_runner.py
pipelines/whale/engine/sql_alchemy_engine.py
pipelines/whale/extractor/metric_runner.py

This PR adds test coverage for sending metric SQL code to SQLAlchemy.
In addition I added some improvements to the documentation.

Add test to metric runner

---

pipelines/requirements.txt
pipelines/tests/unit/extractor/test_metric_runner.py
pipelines/tests/unit/utils/test_sql.py
pipelines/whale/extractor/metric_runner.py
pipelines/whale/models/metric_value.py

Closes https://github.com/dataframehq/whale/issues/80.
Some notes:
- [Slack suggests](https://github.com/slackapi/python-slack-sdk#sending-a-message-to-slack) using the Slack channel id instead of the Slack channel itself. I went through Whale's Slack instance, but failed to find the ID of a channel. Instead of digging further, I decided to allow channel names itself. If it's too difficult for me to find the channel ID, users will likely suffer from the same problem.
- In order to authorize the bot, a token needs to be provided. [Slack's documentation](https://github.com/slackapi/python-slack-sdk#sending-a-message-to-slack) stores this token as an environment variable. **My suggestion is to let users store this token as an environment variable first**. If this alert feature becomes more …

Adding alerts on Slack to metrics

---

pipelines/tests/unit/extractor/test_postgres_metadata_extractor.py
pipelines/whale/extractor/postgres_metadata_extractor.py
pipelines/whale/utils/extractor_wrappers.py

Closes https://github.com/dataframehq/whale/issues/102.
I added the file [`postgres_metadata_extractor.py`](https://github.com/amundsen-io/amundsendatabuilder/blob/master/databuilder/extractor/) from amundsen as well as its [test file](https://github.com/amundsen-io/amundsendatabuilder/blob/master/tests/unit/extractor/test_postgres_metadata_extractor.py). In order for Postgres views to show up, we need to use a `left join` instead of an `inner join` on `pg_catalog.pg_statio_all_tables`. 
FYI:
- For our Postgres instance, this more than doubles the number of tables found.
- I tried to filter out more tables by explicitly filtering for `view` tables by joining on `information_schema.tables`, but this did not change the result.

Adding Postgres views

---

Makefile
cli/src/filesystem.rs

Two small changes:
* Small bug in rust code -- the recent refactor of the `deduplicate_file` function for some reason actually just deletes the manifest used by skim. @biomunky FYI. Sorry I missed this before merge.
* Split up makefile so `make && make rust` can be run to test rust without setting up python env.

fix: broken deduplication.

---

docs/features/metrics.md

See the following documentation:
Renaming everything to `channels`.

Making Slack alert documentation consistent

---

Makefile

Makefile was incorrectly referencing `rust`, not `install_rust`, causing the binary to not be moved to the correct directory in `~/.whale`.

fix: broken makefile

---

Makefile
docs/features/metrics.md
pipelines/dev-requirements.txt
services/slack_access_token.py
services/tests/test_slack_access_token.py

Currently Slack alerts can only be sent to Whale's own Slack workspace. This PR enables users to send Slack alerts to their own workspace.
Some design choices:
- Instead of designing my own front-end, where I display the access token, I just redirect back to our documentation and explain that the token is passed via an URL parameter. Is there a better solution?
- Once merged and deployed we should test the flow and the design of the docs, since I can't see that myself.
Left to do:
- Have some deployment where we call `python3 -m flask run`. 
- Find a way to store `CLIENT_ID` and `CLIENT_SECRET`. That depends a bit on the target infrastructure, so I just put dummy data.

Enable users to use own Slack workspace for Slack alerts

---

cli/src/warehouse/mod.rs
cli/src/warehouse/snowflake.rs
cli/src/warehouse/whutils.rs
pipelines/setup.py
pipelines/tests/unit/utils/test_extractor_wrappers.py
pipelines/whale/models/connection_config.py
pipelines/whale/utils/extractor_wrappers.py

Snowflake onboarding was only semi-functional before this -- the onboarding process was broken (and requested an unnecessary port object), though the connection and scraping worked. This change backwards-compatibly fixes the onboarding process and proper configuration of the extractor using the snowflake jargon.

Fix snowflake onboarding process

---

.github/workflows/cd.yml

Have been meaning to fix this for months now -- I've just been manually making the prereleases full releases out of laziness. Modifying this so people don't end up getting emails about "pre-releases" when they are actually releases.

chore: stop making each tag a prerelease by default

---

pipelines/tests/unit/engine/test_presto_engine.py
pipelines/tests/unit/extractor/test_glue_extractor.py
pipelines/tests/unit/extractor/test_postgres_metadata_extractor.py
pipelines/tests/unit/extractor/test_presto_loop_extractor.py
pipelines/tests/unit/extractor/test_snowflake_metadata_extractor.py
pipelines/tests/unit/extractor/test_spanner_metadata_extractor.py
pipelines/tests/unit/extractor/test_splice_machine_metadata_extractor.py
pipelines/tests/unit/utils/test_extractor_wrappers.py
pipelines/whale/engine/mixins/presto_commands_mixin.py
pipelines/whale/extractor/amundsen_neo4j_metadata_extractor.py
pipelines/whale/extractor/base_postgres_metadata_extractor.py
pipelines/whale/extractor/bigquery_metadata_extractor.py
pipelines/whale/extractor/glue_extractor.py
pipelines/whale/extractor/postgres_metadata_extractor.py
pipelines/whale/extractor/presto_table_metadata_extractor.py
pipelines/whale/extractor/snowflake_metadata_extractor.py
pipelines/whale/extractor/spanner_metadata_extractor.py
pipelines/whale/extractor/splice_machine_metadata_extractor.py
pipelines/whale/loader/whale_loader.py
pipelines/whale/models/column_metadata.py
pipelines/whale/models/presto_watermark.py
pipelines/whale/models/table_column_stats.py
pipelines/whale/models/table_metadata.py

Some cleanup of `table_metadata.py`:
- I pulled `ColumnMetadata` out into a separate file.
- I pulled `TableColumnStats` out into a separate file.
- I renamed `col_type` to `data_type`: It took me some time at first to understand the responsibility of this class attribute and I think the correct term would be `data_type`. 
- In `pipelines/tests/unit/extractor/test_postgres_metadata_extractor.py` I am now importing `PostgresMetadataExtractor` from whale and no longer from the databuilder package. This meant all test cases needed the `is_view` field.
- One small refactor inside `whale_loader.py` which should improve readability

Refactor table metadata file & other small refactors

---

pipelines/tests/unit/extractor/test_postgres_index_extractor.py
pipelines/tests/unit/loader/test_whale_loader.py
pipelines/tests/unit/models/test_index_metadata.py
pipelines/tests/unit/utils/test_extractor_wrappers.py
pipelines/whale/extractor/base_index_extractor.py
pipelines/whale/extractor/base_postgres_metadata_extractor.py
pipelines/whale/extractor/postgres_index_extractor.py
pipelines/whale/loader/whale_loader.py
pipelines/whale/models/index_metadata.py
pipelines/whale/utils/extractor_wrappers.py
pipelines/whale/utils/markdown_delimiters.py
pipelines/whale/utils/parsers.py

This PR adds the ability to scrape index metadata of a PostgreSQL instance, like this:
- I add `add_indexes` to `configure_bigquery_extractor`, which adds index information to the table metadata.
- `add_indexes` adds `PostgresIndexExtractor` as an additional extractor. This is done via a dict, meaning it will be easy to add a e.g. `BigQueryIndexExtractor`.
- `PostgresIndexExtractor` inherits from `IndexExtractor` and expands on `IndexExtractor` by a SQL query that gets all the index information we need, e.g. a list of indexes incl. name & which columns are included in an index.
- `IndexExtractor` itself contains mostly boilerplate code to initiate a connection and interact with the iterator and `SQLAlchemyEngine`.
- Inside `WhaleLoader` `PostgresIndexExtractor` is run, since it was added …

Add index metadata for PostgreSQL

---

pipelines/run_script.py
pipelines/setup.py
pipelines/tests/unit/fixtures.py
pipelines/tests/unit/utils/test_sql.py
pipelines/whale/__init__.py
pipelines/whale/utils/__init__.py
pipelines/whale/utils/paths.py
pipelines/whale/utils/sql.py

* For the `wh run` command, remove prints for markdown files (not for sql files).
* Enable `wh run` to work for markdown files in general (not just in whale). Added logic to detect if it's a whale path to get the database type.

Extend runner functionality, and clean up logging messages

---

cli/Cargo.toml
cli/src/skimmer.rs

Add dash required by Cargo in package version
Please see [issue](https://github.com/dataframehq/whale/issues/158)
Cargo appears to require a hyphen in between the patch version and the pre release identifiers.
Any advice or suggestion is more than welcome.
Thanks

Add hyphen required by Cargo in package version

---

pipelines/README.md
services/tests/test_slack_access_token.py

When CI ran in an earlier merge, it failed. From https://github.com/dataframehq/whale/runs/2622524391:
```
>           raise RuntimeError(_request_ctx_err_msg)
E           RuntimeError: Working outside of request context.
E           
E           This typically means that you attempted to use functionality that needed
E           an active HTTP request.  Consult the documentation on testing for
E           information about how to avoid this problem.
```
Locally I was never able to reproduce the error, but it seems that we need to create a Flask context first to access anything about the request. This is done with `test_request_context`. Since this environment is even more contained, I think the only way to test code is to manually call the method being called on this specific route.

Fix Slack tests

---

docs/features/running-sql-queries.md

Brew sticks the binary in a different place, felt worth calling out as it tripped me up for a sec when i was copypasta'ing this -- considered doing something like {bin location} adding context around the possibilities there but that seemed more confusing tbh

Add brew install location to docs for clarity
